// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorizations.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthorization = `-- name: GetAuthorization :one
SELECT id, tenant_id, card_account_id,
       authorized_amount, authorized_currency,
       captured_amount, captured_currency,
       state, version, created_at, updated_at
FROM spending.authorizations
WHERE tenant_id = $1 AND id = $2
`

type GetAuthorizationParams struct {
	TenantID string    `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

type GetAuthorizationRow struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           string             `json:"tenant_id"`
	CardAccountID      uuid.UUID          `json:"card_account_id"`
	AuthorizedAmount   pgtype.Numeric     `json:"authorized_amount"`
	AuthorizedCurrency string             `json:"authorized_currency"`
	CapturedAmount     pgtype.Numeric     `json:"captured_amount"`
	CapturedCurrency   string             `json:"captured_currency"`
	State              string             `json:"state"`
	Version            int32              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAuthorization(ctx context.Context, arg GetAuthorizationParams) (GetAuthorizationRow, error) {
	row := q.db.QueryRow(ctx, getAuthorization, arg.TenantID, arg.ID)
	var i GetAuthorizationRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CardAccountID,
		&i.AuthorizedAmount,
		&i.AuthorizedCurrency,
		&i.CapturedAmount,
		&i.CapturedCurrency,
		&i.State,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAuthorization = `-- name: InsertAuthorization :exec
INSERT INTO spending.authorizations (
    id, tenant_id, card_account_id,
    authorized_amount, authorized_currency,
    captured_amount, captured_currency,
    state, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 1, NOW(), NOW()
)
`

type InsertAuthorizationParams struct {
	ID                 uuid.UUID      `json:"id"`
	TenantID           string         `json:"tenant_id"`
	CardAccountID      uuid.UUID      `json:"card_account_id"`
	AuthorizedAmount   pgtype.Numeric `json:"authorized_amount"`
	AuthorizedCurrency string         `json:"authorized_currency"`
	CapturedAmount     pgtype.Numeric `json:"captured_amount"`
	CapturedCurrency   string         `json:"captured_currency"`
	State              string         `json:"state"`
}

func (q *Queries) InsertAuthorization(ctx context.Context, arg InsertAuthorizationParams) error {
	_, err := q.db.Exec(ctx, insertAuthorization,
		arg.ID,
		arg.TenantID,
		arg.CardAccountID,
		arg.AuthorizedAmount,
		arg.AuthorizedCurrency,
		arg.CapturedAmount,
		arg.CapturedCurrency,
		arg.State,
	)
	return err
}

const updateAuthorization = `-- name: UpdateAuthorization :execrows
UPDATE spending.authorizations
SET captured_amount = $3,
    state = $4,
    version = version + 1,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND version = $5
`

type UpdateAuthorizationParams struct {
	TenantID       string         `json:"tenant_id"`
	ID             uuid.UUID      `json:"id"`
	CapturedAmount pgtype.Numeric `json:"captured_amount"`
	State          string         `json:"state"`
	Version        int32          `json:"version"`
}

func (q *Queries) UpdateAuthorization(ctx context.Context, arg UpdateAuthorizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAuthorization,
		arg.TenantID,
		arg.ID,
		arg.CapturedAmount,
		arg.State,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
