// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card_account.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCardAccountByID = `-- name: GetCardAccountByID :one
SELECT id, tenant_id,
	   spending_limit_amount, spending_limit_currency,
	   rolling_spend_amount, rolling_spend_currency,
	   version, created_at, updated_at
FROM spending.card_accounts
WHERE id = $1 AND tenant_id = $2
`

type GetCardAccountByIDParams struct {
	ID       uuid.UUID
	TenantID string
}

func (q *Queries) GetCardAccountByID(ctx context.Context, arg GetCardAccountByIDParams) (SpendingCardAccount, error) {
	row := q.db.QueryRow(ctx, getCardAccountByID, arg.ID, arg.TenantID)
	var i SpendingCardAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SpendingLimitAmount,
		&i.SpendingLimitCurrency,
		&i.RollingSpendAmount,
		&i.RollingSpendCurrency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardAccountByTenantID = `-- name: GetCardAccountByTenantID :one
SELECT id, tenant_id,
	   spending_limit_amount, spending_limit_currency,
	   rolling_spend_amount, rolling_spend_currency,
	   version, created_at, updated_at
FROM spending.card_accounts
WHERE tenant_id = $1
LIMIT 1
`

func (q *Queries) GetCardAccountByTenantID(ctx context.Context, tenantID string) (SpendingCardAccount, error) {
	row := q.db.QueryRow(ctx, getCardAccountByTenantID, tenantID)
	var i SpendingCardAccount
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SpendingLimitAmount,
		&i.SpendingLimitCurrency,
		&i.RollingSpendAmount,
		&i.RollingSpendCurrency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCardAccount = `-- name: UpsertCardAccount :execrows
INSERT INTO spending.card_accounts (
	id, tenant_id,
	spending_limit_amount, spending_limit_currency,
	rolling_spend_amount, rolling_spend_currency,
	version, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
	rolling_spend_amount = EXCLUDED.rolling_spend_amount,
	rolling_spend_currency = EXCLUDED.rolling_spend_currency,
	version = EXCLUDED.version,
	updated_at = EXCLUDED.updated_at
WHERE spending.card_accounts.version = EXCLUDED.version - 1
`

type UpsertCardAccountParams struct {
	ID                    uuid.UUID
	TenantID              string
	SpendingLimitAmount   pgtype.Numeric
	SpendingLimitCurrency string
	RollingSpendAmount    pgtype.Numeric
	RollingSpendCurrency  string
	Version               int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) UpsertCardAccount(ctx context.Context, arg UpsertCardAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertCardAccount,
		arg.ID,
		arg.TenantID,
		arg.SpendingLimitAmount,
		arg.SpendingLimitCurrency,
		arg.RollingSpendAmount,
		arg.RollingSpendCurrency,
		arg.Version,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
