// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: card_accounts.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCardAccount = `-- name: GetCardAccount :one
SELECT id, tenant_id,
       spending_limit_amount, spending_limit_currency,
       rolling_spend_amount, rolling_spend_currency,
       version, created_at, updated_at
FROM spending.card_accounts
WHERE tenant_id = $1 AND id = $2
`

type GetCardAccountParams struct {
	TenantID string    `json:"tenant_id"`
	ID       uuid.UUID `json:"id"`
}

type GetCardAccountRow struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              string             `json:"tenant_id"`
	SpendingLimitAmount   pgtype.Numeric     `json:"spending_limit_amount"`
	SpendingLimitCurrency string             `json:"spending_limit_currency"`
	RollingSpendAmount    pgtype.Numeric     `json:"rolling_spend_amount"`
	RollingSpendCurrency  string             `json:"rolling_spend_currency"`
	Version               int32              `json:"version"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCardAccount(ctx context.Context, arg GetCardAccountParams) (GetCardAccountRow, error) {
	row := q.db.QueryRow(ctx, getCardAccount, arg.TenantID, arg.ID)
	var i GetCardAccountRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SpendingLimitAmount,
		&i.SpendingLimitCurrency,
		&i.RollingSpendAmount,
		&i.RollingSpendCurrency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardAccountByTenant = `-- name: GetCardAccountByTenant :one
SELECT id, tenant_id,
       spending_limit_amount, spending_limit_currency,
       rolling_spend_amount, rolling_spend_currency,
       version, created_at, updated_at
FROM spending.card_accounts
WHERE tenant_id = $1
LIMIT 1
`

type GetCardAccountByTenantRow struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              string             `json:"tenant_id"`
	SpendingLimitAmount   pgtype.Numeric     `json:"spending_limit_amount"`
	SpendingLimitCurrency string             `json:"spending_limit_currency"`
	RollingSpendAmount    pgtype.Numeric     `json:"rolling_spend_amount"`
	RollingSpendCurrency  string             `json:"rolling_spend_currency"`
	Version               int32              `json:"version"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCardAccountByTenant(ctx context.Context, tenantID string) (GetCardAccountByTenantRow, error) {
	row := q.db.QueryRow(ctx, getCardAccountByTenant, tenantID)
	var i GetCardAccountByTenantRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SpendingLimitAmount,
		&i.SpendingLimitCurrency,
		&i.RollingSpendAmount,
		&i.RollingSpendCurrency,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCardAccount = `-- name: InsertCardAccount :exec
INSERT INTO spending.card_accounts (
    id, tenant_id,
    spending_limit_amount, spending_limit_currency,
    rolling_spend_amount, rolling_spend_currency,
    version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, 1, NOW(), NOW()
)
`

type InsertCardAccountParams struct {
	ID                    uuid.UUID      `json:"id"`
	TenantID              string         `json:"tenant_id"`
	SpendingLimitAmount   pgtype.Numeric `json:"spending_limit_amount"`
	SpendingLimitCurrency string         `json:"spending_limit_currency"`
	RollingSpendAmount    pgtype.Numeric `json:"rolling_spend_amount"`
	RollingSpendCurrency  string         `json:"rolling_spend_currency"`
}

func (q *Queries) InsertCardAccount(ctx context.Context, arg InsertCardAccountParams) error {
	_, err := q.db.Exec(ctx, insertCardAccount,
		arg.ID,
		arg.TenantID,
		arg.SpendingLimitAmount,
		arg.SpendingLimitCurrency,
		arg.RollingSpendAmount,
		arg.RollingSpendCurrency,
	)
	return err
}

const updateCardAccount = `-- name: UpdateCardAccount :execrows
UPDATE spending.card_accounts
SET rolling_spend_amount = $3,
    version = version + 1,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2 AND version = $4
`

type UpdateCardAccountParams struct {
	TenantID           string         `json:"tenant_id"`
	ID                 uuid.UUID      `json:"id"`
	RollingSpendAmount pgtype.Numeric `json:"rolling_spend_amount"`
	Version            int32          `json:"version"`
}

func (q *Queries) UpdateCardAccount(ctx context.Context, arg UpdateCardAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCardAccount,
		arg.TenantID,
		arg.ID,
		arg.RollingSpendAmount,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
