// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package postgres

import (
	"context"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT tenant_id, idempotency_key, resource_id, status_code, response_body, created_at
FROM spending.idempotency_keys
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetIdempotencyKeyParams struct {
	TenantID       string `json:"tenant_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (SpendingIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i SpendingIdempotencyKey
	err := row.Scan(
		&i.TenantID,
		&i.IdempotencyKey,
		&i.ResourceID,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO spending.idempotency_keys (
    tenant_id, idempotency_key, resource_id, status_code, response_body, created_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
`

type InsertIdempotencyKeyParams struct {
	TenantID       string `json:"tenant_id"`
	IdempotencyKey string `json:"idempotency_key"`
	ResourceID     string `json:"resource_id"`
	StatusCode     int32  `json:"status_code"`
	ResponseBody   []byte `json:"response_body"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.ResourceID,
		arg.StatusCode,
		arg.ResponseBody,
	)
	return err
}

const insertIdempotencyKeyIfAbsent = `-- name: InsertIdempotencyKeyIfAbsent :one
INSERT INTO spending.idempotency_keys (
    tenant_id, idempotency_key, resource_id, status_code, response_body, created_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
RETURNING tenant_id, idempotency_key, resource_id, status_code, response_body, created_at
`

type InsertIdempotencyKeyIfAbsentParams struct {
	TenantID       string `json:"tenant_id"`
	IdempotencyKey string `json:"idempotency_key"`
	ResourceID     string `json:"resource_id"`
	StatusCode     int32  `json:"status_code"`
	ResponseBody   []byte `json:"response_body"`
}

func (q *Queries) InsertIdempotencyKeyIfAbsent(ctx context.Context, arg InsertIdempotencyKeyIfAbsentParams) (SpendingIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKeyIfAbsent,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.ResourceID,
		arg.StatusCode,
		arg.ResponseBody,
	)
	var i SpendingIdempotencyKey
	err := row.Scan(
		&i.TenantID,
		&i.IdempotencyKey,
		&i.ResourceID,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
