// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SpendingAuthorization struct {
	ID                 uuid.UUID
	TenantID           string
	CardAccountID      uuid.UUID
	AuthorizedAmount   pgtype.Numeric
	AuthorizedCurrency string
	CapturedAmount     pgtype.Numeric
	CapturedCurrency   string
	MerchantRef        pgtype.Text
	Reference          pgtype.Text
	State              string
	Version            int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type SpendingCardAccount struct {
	ID                    uuid.UUID
	TenantID              string
	SpendingLimitAmount   pgtype.Numeric
	SpendingLimitCurrency string
	RollingSpendAmount    pgtype.Numeric
	RollingSpendCurrency  string
	Version               int32
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type SpendingIdempotencyKey struct {
	TenantID       string
	IdempotencyKey string
	ResourceID     string
	StatusCode     int32
	ResponseBody   []byte
	CreatedAt      pgtype.Timestamptz
}

type SpendingOutbox struct {
	EventID       string
	EventType     string
	TenantID      string
	CorrelationID pgtype.Text
	CausationID   pgtype.Text
	Payload       []byte
	OccurredAt    pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
}
