// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SpendingAuthorization struct {
	ID                 uuid.UUID          `json:"id"`
	TenantID           string             `json:"tenant_id"`
	CardAccountID      uuid.UUID          `json:"card_account_id"`
	AuthorizedAmount   pgtype.Numeric     `json:"authorized_amount"`
	AuthorizedCurrency string             `json:"authorized_currency"`
	CapturedAmount     pgtype.Numeric     `json:"captured_amount"`
	CapturedCurrency   string             `json:"captured_currency"`
	State              string             `json:"state"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Version            int32              `json:"version"`
}

type SpendingCardAccount struct {
	ID                    uuid.UUID          `json:"id"`
	TenantID              string             `json:"tenant_id"`
	SpendingLimitAmount   pgtype.Numeric     `json:"spending_limit_amount"`
	SpendingLimitCurrency string             `json:"spending_limit_currency"`
	RollingSpendAmount    pgtype.Numeric     `json:"rolling_spend_amount"`
	RollingSpendCurrency  string             `json:"rolling_spend_currency"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	Version               int32              `json:"version"`
}

type SpendingIdempotencyKey struct {
	TenantID       string             `json:"tenant_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	ResourceID     string             `json:"resource_id"`
	StatusCode     int32              `json:"status_code"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
