// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetAuthorizationByID(ctx context.Context, arg GetAuthorizationByIDParams) (GetAuthorizationByIDRow, error)
	GetCardAccountByID(ctx context.Context, arg GetCardAccountByIDParams) (SpendingCardAccount, error)
	GetCardAccountByTenantID(ctx context.Context, tenantID string) (SpendingCardAccount, error)
	GetIdempotencyEntry(ctx context.Context, arg GetIdempotencyEntryParams) (SpendingIdempotencyKey, error)
	InsertIdempotencyIfAbsent(ctx context.Context, arg InsertIdempotencyIfAbsentParams) (InsertIdempotencyIfAbsentRow, error)
	InsertOutboxEntry(ctx context.Context, arg InsertOutboxEntryParams) error
	ListUnpublishedOutbox(ctx context.Context, limit int32) ([]ListUnpublishedOutboxRow, error)
	MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) error
	UpsertAuthorization(ctx context.Context, arg UpsertAuthorizationParams) (int64, error)
	UpsertCardAccount(ctx context.Context, arg UpsertCardAccountParams) (int64, error)
	UpsertIdempotencyEntry(ctx context.Context, arg UpsertIdempotencyEntryParams) error
}

var _ Querier = (*Queries)(nil)
